services:
  postgres:
    image: postgis/postgis:17-3.5
    container_name: smart-water-postgres

    environment:
      POSTGRES_DB: ${POSTGRES_DB:?Set POSTGRES_DB in infrastructure/postgres/.env}
      POSTGRES_USER: ${POSTGRES_USER:?Set POSTGRES_USER in infrastructure/postgres/.env}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Set POSTGRES_PASSWORD in infrastructure/postgres/.env}

    volumes:
      - smart_water_postgres_data:/var/lib/postgresql/data

    ports:
      - "5433:5432"

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - smart-water-network


volumes:
  smart_water_postgres_data:


networks:
  smart-water-network:
    external: true