services:
  postgres:
    image: postgis/postgis:17-3.5
    container_name: smart-water-postgres

    ports:
      - "5433:5432"

    environment:
      POSTGRES_DB: smart_water
      POSTGRES_USER: smart_water_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - smart_water_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U smart_water_user -d smart_water"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - smart-water-network


volumes:
  smart_water_postgres_data:


networks:
  smart-water-network:
    external: true